language: php
php:
  - 5.4

before_script:
  - composer self-update
  - composer install --dev

script:
  - wget http://codeception.com/codecept.phar
  - php codecept.phar build
  - php codecept.phar run